### ISSUE TITLE
Age/weight accept negative numbers

### ISSUE THREAD

**Issue by RazziaJA** [HarmoniaHoldings/medfinder#1]
The fields for age and weight accept negative numbers. It still searches successfully, but seems nonsensical.

Steps to reproduce:
1. Navigate to the consumer portal.
2. Enter a negative number for minimum age or weight.
3. Click search.
4. Observe the lack of error message.

**Comment by keaganADS** [comment]
Fixed in https://github.com/HarmoniaHoldings/medfinder/commit/744dbd9eda52ef3b0620ac8c83a76e8c22329da1
