### ISSUE TITLE
Ranges don't require min <= max

### ISSUE THREAD

**Issue by RazziaJA** [HarmoniaHoldings/medfinder#2]
The parameters that search on a range of values, age and weight, don't require that the minimum value be less than or equal to the maximum value. It still searches successfully, but of course doesn't find any results.

Steps to reproduce:
1. Navigate to the consumer portal.
2. Enter a minimum age.
3. Enter a maximum age less than the minimum.
4. Click search.
5. Observe the lack of error message.

**Comment by HarmoniaHoldings** [comment]
Fixed in https://github.com/HarmoniaHoldings/medfinder/commit/744dbd9eda52ef3b0620ac8c83a76e8c22329da1

**Comment by keaganADS** [comment]
Fixed in https://github.com/HarmoniaHoldings/medfinder/commit/744dbd9eda52ef3b0620ac8c83a76e8c22329da1
