### ISSUE TITLE
Special characters not all handled well

### ISSUE THREAD

**Issue by RazziaJA** [HarmoniaHoldings/medfinder#3]
I tested quite a few special characters in the Brand Name field by preceding the word "tylenol" with each character. 

Five characters failed with a pop-up message saying "Check your request and try again.": '#', '(', ')', '-', ':' (pound, parentheses, hyphen, and colon)
Six characters failed with a pop-up with no message: '!', '@', '$', '*', ';', '/', ',' (exclamation, at, dollar, asterisk, semicolon, forward slash, and comma)

The '&' (ampersand) character failed with the message "Invalid parameter: TYLENOL)"

Four characters returned the same result set, which had three of five entries missing the drug "TYLENOL": '+', '=', ' ', '.' (plus, equals, space, period)

The '_' (underscore) character resulted in a pop-up with the message "No matches found!"

Four characters had no visible effect but caused an IllegalArgumentException in the servlet: '%', '^', '"', '\' (percent, caret, double quote, backslash)

It doesn't seem to be enumerated anywhere which characters might be found in which fields. Looking at some search results I see parentheses, spaces, forward slashes, and hyphens in the brand name field. Manufacturer name additionally has periods, commas, single quotes, double quotes, and ampersands. 
See https://api.fda.gov/drug/event.json?search=safetyreportid:10003301

**Comment by HarmoniaHoldings** [comment]
It seems like these characters '#', '(', ')', '-', ':'  must be disallowed by the OpenFDA API. Even sending them encoded results in the same response. It's probably best for us to just not allow values to contains those characters.

**Comment by keaganADS** [comment]
It seems like these characters '#', '(', ')', '-', ':' must be disallowed by the OpenFDA API. Even sending them encoded results in the same response. It's probably best for us to just not allow values to contains those characters.

**Comment by keaganADS** [comment]
By encoding the &, the invalid parameter error doesn't happen, but now I get the standard "bad request" with no error message back from OpenFDA. It seems they don't handle special characters well at all. I found this http://opendata.stackexchange.com/questions/5503/openfda-bad-request-when-searching-with-url-encoded-inputs where someone was having issues with a single quote and OpenFDA basically said they don't support requests with that character. I'm beginning to assume that is true of all of the characters above that are causing issues for us.

**Comment by keaganADS** [comment]
% seems to be an issues at a variety of levels. JAX-RS/RestEasy seems to be trying to decode it twice. The workaround of adding @Encoded to the method sends it in doubley encoded, which then causes ESAPI's decode to break. I think it would be best to just disallow %'s from being included in any values sent to the server. That doesn't seem like a character that would need to be in the queries for the app anyway.

This https://issues.jboss.org/browse/RESTEASY-326?_sscc=t appears to explain the issue with RestEasy. It seems it was "fixed" for a couple of characters, but not the % sign, which is also affected according to a comment on the bug.

**Comment by keaganADS** [comment]
The "error" case with the _ has been handled more appropriately so it displays no results found in the results table rather than a pop up. It also seems like sometimes no results found comes in as a 200 OK but with the error block in the JSON, so that case is also handled.

**Comment by keaganADS** [comment]
For  '+', '=', ' ', '.' (plus, equals, space, period) I'm not actually seeing a difference in the results between having the symbol in front of tylenol and not. Even just "tylenol" returns two results that only list acetaminophen (active ingredient in tylenol) so I think these symbols are ok.

**Comment by keaganADS** [comment]
Added form validation on client to disallow the following symbols: #()-:!@$*;/,&'"^\

**Comment by keaganADS** [comment]
Forgot to close this on Saturday.
